theme: jekyll-theme-slate
title: Deep Parikh, Upcoming PhD student (Fall 2022), Aerospace Engineering.
description: I am currently a Robotis Developer at MathWorks India. My research interests are Space Robotics, Space systems design and development, On-orbit servicing, Active debris removal, and Autonomous Satelite proximity operations.
